### ISSUE TITLE
Make mosaic from existing picture

### ISSUE THREAD

**Issue by MoreColors123** [Haoming02/sd-webui-mosaic-outpaint#2]
I get some really good results and played around with using the mosaic effect in photoshop as well. It works too, After that i thought It would be a great enhancement for the plugin (and for people without photoshop) if you could just do the mosaic effect on an existing photo in the plugin as well. - but without sizing up the picture in any direction. Maybe by defining a percentage of the height or width that should be mosaiced. 

Edit: what if you made the slider "expand" accept a value of zero?

**Comment by Haoming02** [comment]
**On Hold**

I'll probably add this in a separate block instead

**Comment by Haoming02** [comment]
Please check out the `dev` branch

I added it as a **Script**. When doing `img2img` or `Inpaint`, select the script from the Dropdown to activate it.

**Comment by MoreColors123** [comment]
I'm sorry i just couldn't find out how to do that dev branch pull properly. Can someone chime in?

**Comment by Haoming02** [comment]
The easiesy way would be:
1. Uninstall this Extension (inside your `extensions` folder, remove the `sd-webui-mosaic-outpaint` folder)
2. Launch the Webui
3. Go to the **Extensions** tab
4. Go to **Install with URL**
5. Enter the URL of this repo
6. Enter `dev` in the field for Branch
7. Install as usual

**Comment by MoreColors123** [comment]
OK thanks! Didn't think of that... 

So, I got some pretty good fast results but didn't test it enough yet to be sure if the result is really different from actual inpainting. It seems that the inpainted part is more true to the colors of the original image, which should be the case I think. 

The masked area obviously becomes a rectangular mosaiced block (and how else should it be of course). What inpaint settings do you think are best? I want to play around more with the Denoise value. Here I used 20 steps, CFG 7 and very high denoising (0.97 here), it might benefit from 0.75 or something in that ball park. And I set it to Original, not Fill:

Here is the original picture, which I loaded in Inpaint, then masked the top part (mountains) with the mask tool:
![00002-3591478570](https://github.com/Haoming02/sd-webui-mosaic-outpaint/assets/131474336/55009c8a-ab43-4597-8740-6e1f0f271e3f)
this is the resulting image:
![00014-1092213053](https://github.com/Haoming02/sd-webui-mosaic-outpaint/assets/131474336/79868de4-ad01-4ea3-84cb-c0ad11f47bd7)

this is the resulting mask: 
![tmplf_o8p71](https://github.com/Haoming02/sd-webui-mosaic-outpaint/assets/131474336/f36eca11-63bc-4f17-8564-b14c72b55ee6)

this is the mosaiced version:
![tmpi4qh7ila](https://github.com/Haoming02/sd-webui-mosaic-outpaint/assets/131474336/535536db-d427-4e75-8ed8-19cca4d8f79b)

**Comment by MoreColors123** [comment]
After more testing I definitely think denoising between 0.7 and 0.75 is best. you get different objects with similar colors on the masked parts. WIth lower denoising you see low quality results or even the mosaic is left in place. With higher desnoising you get totally different objects.

**Comment by MoreColors123** [comment]
works fine! not sure about the use case yet, but it does it's job!

original image
![00008-373693443](https://github.com/Haoming02/sd-webui-mosaic-outpaint/assets/131474336/c9d07a67-7884-48e1-bb58-e345bb5fdff5)

resulting image
![00053-30715071](https://github.com/Haoming02/sd-webui-mosaic-outpaint/assets/131474336/c7793a2d-1c4f-4a9a-a7a6-33e12db2117e)

mosaic
![tmpy_yd9ks3](https://github.com/Haoming02/sd-webui-mosaic-outpaint/assets/131474336/839ba321-5cef-4832-958b-f320518420c6)

resulting mask
![tmp_ucbc3t4](https://github.com/Haoming02/sd-webui-mosaic-outpaint/assets/131474336/c00322c8-1d34-4d86-bf05-f05c0bacbed8)

**Comment by Haoming02** [comment]
In your `sysinfo`, your seem to be using an outdated version of this Extension.

Did you click **Check for updates** in the **Extensions** tab?

If so, and it doesn't show a newer commit... this could be a problem...

I did some shenanigans and renamed the branches before. Does the Webui lose track of the latest version...?

**Comment by Haoming02** [comment]
Hmm. I can probably add another text field for **batch from folder**.
