### ISSUE TITLE
[Feature Request] - Allow for 2 or more directions to be extended at the same time

### ISSUE THREAD

**Issue by CCpt5** [Haoming02/sd-webui-mosaic-outpaint#3]
First of all, great job on this implementation - works really well!

If possible I'd love to see a future version have the option to toggle on more than 1 direction to expand an image. So clicking a direction wouldn't change the direction to that one, it's just either "on/off" it from the outputted mask.  
  
I'm not sure if the technique is restricted from doing this based on how the mosaic works. There's a beta version of "Lama Cleaner" (renamed IOPaint) that does this though w/ a feature called ["Extender"]. It'd be awesome if the same thing could be done in A1111 using this extension.

Thanks for the time/effort on this....

Extender image:  
<details><summary>Details</summary>
<p>

![4654654651](https://github.com/Haoming02/sd-webui-mosaic-outpaint/assets/37972078/eb8d63d2-9802-44c3-a555-0842b215476a)

</p>
</details>

**Comment by Haoming02** [comment]
Hello, could you give the `dev` branch a try?

**Comment by Haoming02** [comment]
Good call. I only did it this way cause clockwise XD
