### ISSUE TITLE
[Feature Request] - Add 'Send to Controlnet's Mask' feature

### ISSUE THREAD

**Issue by enternalsaga** [Haoming02/sd-webui-mosaic-outpaint#4]
Hi, Since [Controlnet Allow mask upload](https://github.com/Mikubill/sd-webui-controlnet/pull/2464#issue-2080040574), can you add a button to send those mosaic and mask inputs directly to Controlnet input image and mask please?
Thank you.

**Comment by Haoming02** [comment]
Hello, please try out the `dev` branch~

**Comment by Haoming02** [comment]
*(btw, due to how ControlNet works, the source image may not show up. Simple click the **Clear** mask button to refresh it)*

**Comment by enternalsaga** [comment]
thank you. I gave it a try and it does work. However due to the nature of CN itself there's clear seam around the edge. I will test it on XL soon.
![image](https://github.com/Haoming02/sd-webui-mosaic-outpaint/assets/31148570/56aac453-5c2c-4cac-82f4-39448c0589cd)
![image](https://github.com/Haoming02/sd-webui-mosaic-outpaint/assets/31148570/8826ae1c-8675-4706-b4a2-459787ba5ba8)

**Comment by Haoming02** [comment]
Funnily, all I've got were results like this:
https://github.com/Mikubill/sd-webui-controlnet/issues/2625

Glad that at least it works better for you.

Also, iirc there isn't an Inpaint ControlNet model for SDXL yet...
