### ISSUE TITLE
[Enhancement Req] - Incorporate "Differential Diffusion"? (Re: Soft inpainting)

### ISSUE THREAD

**Issue by CCpt5** [Haoming02/sd-webui-mosaic-outpaint#6]
Hello!

I'm not a developer so I'm not sure if this even makes sense, but is there any chance this new Differential Diffusion method (https://github.com/exx8/differential-diffusion?tab=readme-ov-file) could be incorporated into your extension (or perhaps even just as a new extension)? I trialed the huggingface demo using an image from my HD and just one of their sample soft-painting masks (Whcih doesn't even match my image). Generating w/ the softpainted mask led to some cool results, and soft painting is now available in both the Forge fork of A1111 and the current release candidate for A1111 v1.8.  
  
Here's their demo: https://huggingface.co/spaces/exx8/differential-diffusion

Thanks for considering if this method could add functionality to the cool extension you've developed here, or perhaps could be incorporated into a stand alone extension for A1111.

**Comment by Haoming02** [comment]
I've never used `Soft Inpainting` myself. But **Forge** does have a toggle for it in the `img2img` tab.

Does this Extension not work with it? Or is it missing something?
