### ISSUE TITLE
Could the new "Soft Inpainting" feature in A1111 v1.9 improve this extension?

### ISSUE THREAD

**Issue by CCpt5** [Haoming02/sd-webui-mosaic-outpaint#7]
The latest version of A1111 added a feature for "Soft Inpainting" where masks w/ gradients are interpreted by the UI as opposed to just a binary white/black.  
  
Thread on the subject on the A1111 repo: https://github.com/AUTOMATIC1111/stable-diffusion-webui/discussions/14888 

Just curious if you've ever considered attempting to add support for a gradient mask? Perhaps that would allow for better blending in some instances.  
  
Thanks for any insight!!

![sdfsdfsdfds](https://github.com/Haoming02/sd-webui-mosaic-outpaint/assets/37972078/11f8639c-5f47-42e9-a1fd-30ab1423593e)

**Comment by Haoming02** [comment]
???
Why did you close it?

**Comment by Haoming02** [comment]
It's aight
I just didn't have time to look into it yet
